### ISSUE TITLE
Improve indexing of physDesc in MSS with multiple parts

### ISSUE THREAD

**Issue by ahankinson** [bodleian/fihrist-mss#12]
Example here:
http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_5579

In multipart MSS (those using `msPart`) there may be multiple repeated descriptions in the notes, but without indication of which part they belong to; the notes should probably be qualified with something like:

**Part A:** [NOTE TEXT]
**Part B:** [NOTE TEXT]

etc.

Qualifying the parts should also be applied across all other types of descriptions (layout, extent, etc.)

**Comment by andrew-morrison** [comment]
This will be fixed by switching Fihrist to displaying manuscripts using HTML generated by convert2HTML.xsl.

This may be a good example of the kind of customization that might be desirable. Currently, the way the XSLT has been set up for Medieval displays parts under headings of "Manuscript Part 1", "Manuscript Part 2", etc. It does **not** use the part numbering/labelling as catalogued in the TEI ("A", "B", etc in the example above).

If those differences aren't arbitrary or unimportant, then it can be handled with the system I've set up in bodleian/consolidated-tei-schema#4

**Comment by holfordm** [comment]
See https://github.com/bodleian/medieval-mss/issues/96 - this is something we'd like to change in the medieval catalogue as well!

**Comment by andrew-morrison** [comment]
OK, in that case it is definitely worth my rewriting the part of the XSLT that handles these sorts of headings. Even if everyone wants the same thing, it is a bit of a mess at the moment.

**Comment by andrew-morrison** [comment]
Now Fihrist has the HTML view, display of parts can be customized in their XSLT.
