### ISSUE TITLE
Search and replace repository values

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#25]
Search and replace <repository>University Library</repository> in the Cambridge collection.

There are others with ambiguous repository names:

    "Library" used by Royal Asiatic Society of Great Britain and Ireland
    "Old Library" used by Jesus College, Cambridge

Should someone ask them what they want displayed after their classmarks?

**Comment by andrew-morrison** [comment]
Also, @eifionjones to search and replace `<repository>University Library</repository>` in the Cambridge collection. But there are others with ambiguous repository names:

- "Library" used by Royal Asiatic Society of Great Britain and Ireland
- "Old Library" used by Jesus College, Cambridge

Should someone ask them what they want displayed after their classmarks?

**Comment by andrew-morrison** [comment]
Just realized this is a duplicate of #11

**Comment by andrew-morrison** [comment]
Renamed this issue to focus on the data fix, as it was a duplicate.

**Comment by eifionjones** [comment]
Just taking a look at this, and it looks like across the data set, the best solution would be either to use a concatenation of repository and institution - i.e. repository, institution
Or if that's not possible, just the institution on its own
Does this sound ok? Otherwise I'd just be changing the repository value to match the institution value which means we'd lose data, or putting the concatenation of the two values in repository which means we'd be duplicating data

**Comment by andrew-morrison** [comment]
Implemented on QA. It'll concatenate the repository and institution unless they are identical (I think just the Arabic Commentaries on the Hippocratic Aphorisms project.)

**Comment by eifionjones** [comment]
Excellent, that looks great
