### ISSUE TITLE
Format HTML

### ISSUE THREAD

**Issue by IgnatG** [bodleian/fihrist-mss#41]
On individual items page, there are various tags that need changing. I can style them with CSS but that would be a workaround rather than a fix.
1) http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_7910 - there is an element at the top with a class `msSummary`. It needs to be changed from `<h4>` to `<p>`

2) same URL (http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_7910) - there is an `<ul class="list">` tag. But it's not displaying anything - the text is coloured white by default by Blacklight. How is the text meant to be displayed? If it's a list item, then can we change the `<div>` tags inside the `<ul>` to be `<li>`?

**Comment by IgnatG** [comment]
2) another example http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_7721 under `additions`

**Comment by andrew-morrison** [comment]
I'll look into part 2 of this - `div` elements that should be converted to `li` - later this week, when I've caught up with other projects. This is a bug that should be fixed in the common XSLT shared by all TEI catalogues.

But part 1 - TEI `summary` elements being transformed into HTML `h4` - looks like a deliberate choice in the XSL. Most occurrences in other catalogues are pretty short, and title-like. It appears to be only really Fihrist that has long tracts in `summary` elements (and it varies by the collection, with only ~10% of all Fihrist TEI files having it at all.) So perhaps this is something for @eifionjones to take a decision on whether to add a template for `msContents/summary` in [https://github.com/bodleian/fihrist-mss/blob/master/processing/convert2HTML.xsl](convert2HTML.xsl) to override and output these as `p` HTML tags in Fihrist only?

**Comment by holfordm** [comment]
I don't know what file this is, so haven't seen the data, but could we refine the rule so that, for example, is `<summary>` contains a `<p>` then it should be outputted as a paragraph rather than a header?
I've just reviewed and updated the use of `<summary>` in the medieval catalogue and there are a couple of cases most notably https://medieval.bodleian.ox.ac.uk/catalog/manuscript_3957 where the current output looks odd.

**Comment by andrew-morrison** [comment]
@IgnatG: Here are some new HTML classes if you want to tweak their style:

- h4.msSummary
- div.msSummary
- ul.mslist
- li.mslistitem
- span.mslabel

It was the class of "label" which was clashing with some other class name for which the CSS contains an instruction to colour the text white.

**Comment by IgnatG** [comment]
It's better now. I'll add some styling for them shortly

**Comment by andrew-morrison** [comment]
@IgnatG: I notice you added some CSS for msSummary, mslabel and mslist last week. Those changes have been deployed. Can this issue now be closed?

**Comment by IgnatG** [comment]
yes. all good
