### ISSUE TITLE
Add more information to manuscript entries in search results

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#44]
As requested by Peter Colvin on the Fihrist mailing list:

> If, for example, I search under SOAS for ithe Chagatai mss, 6 come up, but they are now just a list of manuscript numbers (ms. 1546 for example) unlike the old Fihrist which gives you a title and author as well as the manuscript number and is therefore much quicker and easier to browse through. 

As Yasmin points out, if you are looking for works then you can go to the Works button and still filter on the Chagatai language and SOAS institution, and get the 7 works (one of the 6 manuscripts contains two works.) But clicking on the Classmarks button then searching or filtering does give you little clue as to what each manuscript contains. 

We could add a second line under each manuscript in the search results, displaying the `msContents/summary` from the TEI (or, say, the first 128 characters, because some of them are very long). But only ~15% of manuscript descriptions have one. I could write a batch conversion script to add them to the ~85% that don't, containing a statement of the number of works and authors, or the title of the work and the name of the author if there is only one. Anything more would make the search results too cluttered (and the aim is to give people a hint as to the contents, not turn the search results pages into comprehensive catalogues themselves.)

The result would look something like this:

![Search for SOAS manuscript in Chagati](https://user-images.githubusercontent.com/33721187/37036104-93512126-2146-11e8-9f00-8e5a510cacc9.png)

However, there would be a lot of manuscripts which would just have something like:

> Contents:    1 copy of "al-Qurʼān"

Or:

> Contents:    5 works by 4 authors

But even those provide some clue as to what you're likely to see if you click on them.

The point of batch converting them, rather than building the summary dynamically each time the collections are re-indexed, is that people would be able to revise or expand upon them, by editing the summary in their TEI files. But maybe that would be a step too far?

@eifionjones: Is this worth doing?

@holfordm: Do you think this would be useful in Medieval and other TEI catalogues?

**Comment by eifionjones** [comment]
I think this looks great! Can I just run it past Yasmin and get back to you (hopefully today)?

**Comment by holfordm** [comment]
I think this could be very helpful, as long as it doesn't clutter the display, and would definitely be worth trialing on medieval. I think we would want to include the information in `<origin>` as well as author/title, and the logic would be a little different since we tend to use `<head>` rather than `<summary>` for the summary description. The logic would be something like
-if there is a `<head>` just take the content of that
-for authors/titles:
--if there are authors that are children of `<msItem>`, take the first 2 names; if there are more, or items without authors, add 'etc.'
--if there are no msItems with authors, take the first (1 or 2?) title(s?) and if there are more, add 'etc.'
-for origin: just take the text content of `<origin>` (adding the semi colon between date and place if necessary)
For example:
MS. Add. A. 5
Nicholas de Auximo, Antoninus of Florence        15th century; Italian

MS. Add. A. 12
Petrarch, etc.               15th century, second half; Italian

MS. Add. A. 106
Medical recipes. Religious poems.          15th century; English, North

MS. Bodl. 34
Life of St. Katherine of Alexandria. Life of St. Margaret of Antioch; etc.    13th century, early; English

-in the case of `<msPart>` probably just say "Composite manuscript" and leave it at that?

**Comment by andrew-morrison** [comment]
@eifionjones:  I need to work on some other projects today, but I'll return to this tomorrow.

@holfordm: I can set that up on the Medieval QA site later this week. I've created an issue over in the medieval-mss repository, so I can tag my commits to that.

**Comment by eifionjones** [comment]
Hi Andrew - I've spoken to Yasmin and we think it's a great idea! Thanks

**Comment by andrew-morrison** [comment]
OK. I'll fix on the issues [I've tagged as bugs](https://github.com/bodleian/fihrist-mss/labels/bug) first, then work on this.

**Comment by andrew-morrison** [comment]
A draft version of this is now on the Fihrist QA site.

**Comment by eifionjones** [comment]
Also looks good to me! Thanks again

**Comment by andrew-morrison** [comment]
I've run this, with a few more tweaks. For example, when the work title begins with some variant of "Dīvān-i" (e.g. "Dīwān-i Khwushḥāl Khān"), it doesn't add the author name, because that would seem to be redundant (roughly equivalent to "Shakespeare's Sonnets by William Shakespeare".)

It is now on both the QA and production Fihrist web sites.
